default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 20

development:
  <<: *default
  database: wallet_system_dvlpt

test:
  <<: *default
  database: wallet_system_test

# production:
#   <<: *default
#   database: wallet_system_prod
